{% set version = "0.5.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggmuller
  version: {{ version|replace("-", "_") }}

source:
  fn: ggmuller_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggmuller_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggmuller/ggmuller_{{ version }}.tar.gz
  sha256: 1d882a1388b6fc4e2a8b50bc79fcd4caa72c141b202967fc650ac5525daaeb78

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ape
    - r-dplyr >=0.7.0
    - r-ggplot2

  run:
    - r-base
    - r-ape
    - r-dplyr >=0.7.0
    - r-ggplot2

test:
  commands:
    - $R -e "library('ggmuller')"  # [not win]
    - "\"%R%\" -e \"library('ggmuller')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggmuller
  license: MIT
  summary: Create plots that combine a phylogeny and frequency dynamics. Phylogenetic input can
    be a generic adjacency matrix or a tree of class "phylo". Inspired by similar plots
    in publications of the labs of RE Lenski and JE Barrick. Named for HJ Muller (who
    popularised such plots) and H Wickham (whose code this package exploits).
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
