{% set version = "0.5.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggmuller
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggmuller_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggmuller/ggmuller_{{ version }}.tar.gz
  sha256: ca20d3ee33d282af761b2084144abe2e5dc0e40e86e559a7187f2e9a1c373e19

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ape
    - r-dplyr >=0.7.0
    - r-ggplot2
  run:
    - r-base
    - r-ape
    - r-dplyr >=0.7.0
    - r-ggplot2

test:
  commands:
    - $R -e "library('ggmuller')"           # [not win]
    - "\"%R%\" -e \"library('ggmuller')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggmuller
  license: MIT
  summary: Create plots that combine a phylogeny and frequency dynamics. Phylogenetic input can be a generic adjacency matrix or a tree of class "phylo". Inspired by similar plots in publications of the labs of RE Lenski and JE Barrick. Named for HJ Muller (who popularised such plots) and H Wickham (whose code this package
    exploits).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggmuller
# Title: Create Muller Plots of Evolutionary Dynamics
# Version: 0.5.4
# Authors@R: person("Robert", "Noble", email = "robjohnnoble@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8057-4252"))
# Description: Create plots that combine a phylogeny and frequency dynamics. Phylogenetic input can be a generic adjacency matrix or a tree of class "phylo". Inspired by similar plots in publications of the labs of RE Lenski and JE Barrick. Named for HJ Muller (who popularised such plots) and H Wickham (whose code this package exploits).
# Depends: R (>= 3.2.0)
# Imports: dplyr (>= 0.7.0), ggplot2, ape
# Suggests: RColorBrewer, knitr, rmarkdown
# VignetteBuilder: knitr
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-04 13:10:48 UTC; rnoble
# Author: Robert Noble [aut, cre] (<https://orcid.org/0000-0002-8057-4252>)
# Maintainer: Robert Noble <robjohnnoble@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-05 02:10:17 UTC
