travis:
  secure:
    BINSTAR_TOKEN: UAmTCed1cJfRKgHuR7H9uqudgwQLz6Te56i7HWO7K+iRMmOj34HHz4o6Cr0Ot+eb7Iziq5n5vsQynr1tSMRGIjwRO1kGTD6Yb4xq5R5KLqCf3NcuUY2jEZiZOpsRzu3jSk1nRwiOx2SLauoQR5RGWP9Ri/5IhfcnAVeSzsjsQ6I19542O6rZeed9yiXDZr5W36oKZ3yMoPu3Wei7vIv2ZC07vzQjSeeEDutU/pLSByJV0IQEtqMsgFEkmRUoQKL+YUGHHxAgmQBL3TKzW9f5aaaQ47ulLBPvo6730B2Qq+s1sTZlRtUW5zY2JPFOFb+chfPlwiyz+Fcg/xYAANSzgY6n6qmM+l4EDqk6V1mbK7ljNuy3GMfgYq151TO+fHRn/8ZRcjuBbo+5EuGN2b7LIUULGBZP0ahtTW4S4Y5LKJ09baqsXoI0tXnA2Z+GQYRgS+QzHqMdz4SSQRKVLkTBVxsas8AYmTNyqHhu0+RJzbv1cG/EC5rK5F2ZoKB2PwhEjEW0MYKy6GV29Q8EkM05Ipz33TlBHEdJWQ8uFdURl24RnYtSAzGOWMIhfPlb7BUr5MiQukIgnDMTzTShNjX7mM2zNYIDdloA9ePf8bFqxCig1+e6yXu8LkVlGgDsJ3WyFVtKIB5tSCPX6DjjG/XowudxZl2sYceVSq83Noh9xv4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
