appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WRxYOb8GjIwokSec0fCY2oWMLLTykg+Gqkcv/UxdW16uCrRKNcERI3igjVKXCnT7jHmzEiytxJBllR4ot/U4LxHR2aMGaco2clKabhNZcgMSMGhC2/WEtBZKXgl6qLvhJtXKYhSUPVEF1J7xDep/UXsFE1f0IJ3j7edGAZcGQ3aQnJh9JAt+oQxxl0eoJxi3oIpE2Z1z0GKSmSNIvAJS9wpsU3nU64l7ztPR9rxd81+ge1GCY0Uh2W+DHBvaiFXxSf1w6pxNqYYbD59HLFY/h6SGqy0TS+Zi/kHxbvgeCfV8u0iE9eHNrfz11wwhQgqnYQgnBGnllXRE4ivrGOKypaoXMCSKTwHfVoeZZo48rB1X0cr5H4jah5w4I5V0vUFRRl79G/2B72vmAm7/ZCJE+hPLiB322MADSxD2U+yjMuMsExbKEo45L7KVDpPGuaHVL/5L3tDEXznM2/WtVhPqtLvYFMYKg4LmbyUWjQHSWO+ZFJc5a0/zNxvGgjmXvoVM4zFPyCbGJhEdL2CydnelbxyuQ+igCYWvjp0hya0JORrA3HrjJd8FTa4wz4WJDTmuV6+uAFz9BshCaA3QZZ4r0Vc2iYZdtvBRLshnKZsLdaW4RYQWxQHfp1zWlM7j3GdvhsWLu99hphvq70+UdH9xo5cCe383L7UBmu7bi+i+/To=}
